name: logic_lab
description: Fauzi — Senior Mobile Application Engineer Portfolio
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  responsive_framework: ^1.4.0
  google_fonts: ^6.2.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
